<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
// $config['base_url'] = '';
// $config['uri_segment'] = 3;
$config['num_links'] = 4;
$config['page_query_string'] = TRUE;
$config['reuse_query_string'] = TRUE;
$config['query_string_segment'] = 'page';
$config['full_tag_open'] = '<div style="margin-bottom: 10px;" class="pagination-container margin-top-20 margin-bottom-40"><nav class=""><ul class="pagination category-pagination">';
$config['full_tag_close'] = '</ul></nav></div>';
$config['first_link'] = '&laquo;';
$config['first_tag_open'] = '<li class="prev page">';
$config['first_tag_close'] = '</li>';
$config['last_link'] = '&raquo;';
$config['last_tag_open'] = '<li class="last page"><i class="fa fa-long-arrow-right"></i>';
$config['last_tag_close'] = '</li>';
$config['next_link'] = ' &rarr;';
$config['next_tag_open'] = '<li class="next page">';
$config['next_tag_close'] = '</li>';
$config['prev_link'] = '&larr; ';
$config['prev_tag_open'] = '<li class="prev page">';
$config['prev_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li class="active"><a href="">';
$config['cur_tag_close'] = '</a></li>';
$config['num_tag_open'] = '<li class="page">';
$config['num_tag_close'] = '</li>';
$config['use_page_numbers'] = TRUE;
// $config['display_pages'] = FALSE;
// 
// $config['anchor_class'] = 'follow_link';
